language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  edge: true # opt into v2 beta
  target_branch: master
  local_dir: public
  cleanup: false
  token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  commit_message: "TravisCI Deploy: ${TRAVIS_COMMIT}"
  on:
    branch: develop
