name: Build and Deploy
on:
  push:
    branches:
      - develop

jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      # - name: Checkout Master Branch
      #   uses: actions/checkout@v2
      #   with:
      #     ref: master
      #     persist-credentials: false

      # - name: Remove All Files # remove files currently in master branch (Old build files)
      #   run: |
      #     rm -rf *

      - name: Checkout Develop Branch # checkout dev branch
        uses: actions/checkout@v2
        with:
          ref: develop
          path: temp
          persist-credentials: false
      
      # - name: Setup Dependencies Cache
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      #     cache: 'yarn'

      - name: Install Dependencies and Build
        run: |
          cd temp
          yarn install
          yarn build


      - name: Move files # move the dist files into root dir and remove others
        run: |
          mv temp/dist/* ./
          rm -rf temp

      - name: Commit Files For Change # commit new build files
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build release"

      - name: Push Changes To Master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true