on:
  push:
    branches:
      - develop

jobs:
  job1:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout master branch # checkout master branch
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: remove all files # remove files currently in master branch (Old build files).
        run: |
          rm -rf *
      - name: checkout dev branch # checkout dev branch into temp folder.
        uses: actions/checkout@v2
        with:
          path: temp
          persist-credentials: false
      - name: Build project # go to temp folder and build to create files.
        run: |
          cd temp
          yarn build
      - name: move files # move the dist files into root dir and remove others.
        run: |
          mv temp/dist/* ./
          rm -rf temp
      - name: Commit files for change # commit new build files
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Add changes"
      - name: Push changes # push files into master branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true